# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20170302_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='joins',
            field=models.ManyToManyField(related_name='add_freinds', to='belt.User'),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='friend_key', to='belt.User'),
            preserve_default=False,
        ),
    ]
