# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_email_val_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_val',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
