# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='joins',
        ),
        migrations.AddField(
            model_name='friend',
            name='freind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freind', to='belt.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='belt.User'),
        ),
    ]
