# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp_app', '0002_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travelend',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelstart',
            field=models.DateField(),
        ),
    ]
