# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_key', to='belt.User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_key', to='belt.User')),
            ],
        ),
    ]
