# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
